server:
  port: 8080
  #address: 0.0.0.0

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: ${device.datasource.driver-class-name}
      url: jdbc:mysql://${device.datasource.host}:${device.datasource.port}/${device.datasource.database}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: ${device.datasource.username}
      password: ${device.datasource.password}
  redis:
    host: ${device.redis.host}
    port: ${device.redis.port}
    password: ${device.redis.password}
    database: ${device.redis.database}
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.device
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      device:
        mapper: debug
        service: info
        controller: info

device:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: buyaozaizhengle
    # 设置jwt过期时间
    admin-ttl: 720000000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token
  alioss:
    endpoint: ${device.alioss.endpoint}
    access-key-id: ${device.alioss.access-key-id}
    access-key-secret: ${device.alioss.access-key-secret}
    bucket-name: ${device.alioss.bucket-name}
  wechat:
    appid: ${device.wechat.appid}
    secret: ${device.wechat.secret}
    mch_id: ${device.wechat.mch_id}
    mchSerialNo: ${device.wechat.mchSerialNo}
    privateKeyFilePath: ${device.wechat.privateKeyFilePath}
    apiV3Key: ${device.wechat.apiV3Key}
    weChatPayCertFilePath: ${device.wechat.weChatPayCertFilePath}
    notifyUrl: ${device.wechat.notifyUrl}
    refundNotifyUrl: ${device.wechat.refundNotifyUrl}
  shop:
    address: 北京市海淀区上地十街10号
  baidu:
    appId: ${device.baidu.appId}
    key: ${device.baidu.key}
    secret: ${device.baidu.secret}

